Repository benfl3713/DepartureBoard, pull requests merged in 2020-11, with the labels that each got.

#157 Added Admin Navbar Link
  DepartureBoardWeb/ClientApp/src/app/nav-menu/nav-menu.component.html
Labels: enhancement

#158 Added search options
  DepartureBoardWeb/ClientApp/src/app/search/search.component.css
  DepartureBoardWeb/ClientApp/src/app/search/search.component.html
  DepartureBoardWeb/ClientApp/src/app/search/search.component.ts
Labels: enhancement

#159 Fixed singleboard scrolling row issues
  DepartureBoardWeb/ClientApp/src/app/Components/departure-scroller/departure-scroller.component.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/singleboard/singleboard.html
  DepartureBoardWeb/ClientApp/src/app/Pages/singleboard/singleboard.ts
  DepartureBoardWeb/ClientApp/src/app/search/search.component.css
  TrainDataAPI/DataSource/RealTimeTrainsAPI.cs
Labels: enhancement

#160 Added news as separate list file
  DepartureBoardWeb/ClientApp/src/app/Utils/routetransformer.directive.ts
  DepartureBoardWeb/ClientApp/src/app/app.module.ts
  DepartureBoardWeb/ClientApp/src/app/widgets/news/news.component.html
  DepartureBoardWeb/ClientApp/src/app/widgets/news/news.component.ts
  DepartureBoardWeb/ClientApp/src/app/widgets/news/news.items.ts
Labels: enhancement

#162 Fixed singleboard when platform data not present
  .github/ISSUE_TEMPLATE/bugfix.md
  .github/ISSUE_TEMPLATE/feature.md
  DepartureBoardWeb/ClientApp/src/app/Components/departure-scroller/departure-scroller.component.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/singleboard/singleboard.ts
  DepartureBoardWeb/ClientApp/src/app/widgets/coming-soon/coming-soon.component.html
  DepartureBoardWeb/ClientApp/src/app/widgets/coming-soon/coming-soon.component.ts
  DepartureBoardWeb/ClientApp/src/app/widgets/coming-soon/coming-soon.items.ts
  DepartureBoardWeb/ClientApp/src/app/widgets/news/news.items.ts
Labels: bug

#164 Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#166 General Code Cleanup of json responses
  .vscode/launch.json
  DepartureBoardWeb/ClientApp/src/app/Pages/boards/board/board.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/boards/boards.component.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/singleboard/singleboard.ts
  DepartureBoardWeb/ClientApp/src/app/Services/departure.service.ts
  DepartureBoardWeb/ClientApp/src/app/models/departure.model.ts
  DepartureBoardWeb/ClientApp/src/app/models/singleboard-response.model.ts
  DepartureBoardWeb/ClientApp/src/tslint.json
Labels: technical

#168 Fixed Hamburger Menu z-index
  DepartureBoardWeb/ClientApp/src/app/nav-menu/nav-menu.component.css
  DepartureBoardWeb/ClientApp/src/app/nav-menu/nav-menu.component.html
Labels: bug

#170 German Departure Beta Features
  DepartureBoardCore/ConfigService.cs
  DepartureBoardWeb/ClientApp/package-lock.json
  DepartureBoardWeb/ClientApp/package.json
  DepartureBoardWeb/ClientApp/src/app/Guards/beta-features.guard.spec.ts
  DepartureBoardWeb/ClientApp/src/app/Guards/beta-features.guard.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/germany/germany-singleboard/germany-singleboard.component.css
  DepartureBoardWeb/ClientApp/src/app/Pages/germany/germany-singleboard/germany-singleboard.component.html
  DepartureBoardWeb/ClientApp/src/app/Pages/germany/germany-singleboard/germany-singleboard.component.spec.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/germany/germany-singleboard/germany-singleboard.component.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/germany/germany.module.ts
  DepartureBoardWeb/ClientApp/src/app/Services/departure.service.ts
  DepartureBoardWeb/ClientApp/src/app/Services/station-lookup.service.ts
  DepartureBoardWeb/ClientApp/src/app/app.component.ts
  DepartureBoardWeb/ClientApp/src/app/app.module.ts
  DepartureBoardWeb/ClientApp/src/app/models/departure.model.ts
  DepartureBoardWeb/ClientApp/src/app/models/station.model.ts
  DepartureBoardWeb/ClientApp/src/app/search/search.component.html
  DepartureBoardWeb/ClientApp/src/app/search/search.component.ts
  DepartureBoardWeb/ClientApp/src/app/settings/settings.component.html
  DepartureBoardWeb/ClientApp/src/app/settings/settings.component.ts
  DepartureBoardWeb/ClientApp/src/app/widgets/coming-soon/coming-soon.component.html
  DepartureBoardWeb/ClientApp/src/app/widgets/coming-soon/coming-soon.items.ts
  DepartureBoardWeb/Controllers/LiveDeparturesController.cs
  DepartureBoardWeb/Controllers/StationLookupController.cs
  TrainDataAPI/DataSource/DeutscheBahnAPI.cs
  TrainDataAPI/DataSource/NationalRailAPI.cs
  TrainDataAPI/DataSource/RealTimeTrainsAPI.cs
  TrainDataAPI/DataSource/TransportAPI.cs
  TrainDataAPI/Departure.cs
  TrainDataAPI/Services/StationLookup.cs
  TrainDataAPI/StationStop.cs
  TrainDataAPITests/DepartureTests.cs
Labels: enhancement

#172 Fixed german scrolling text
  DepartureBoardWeb/ClientApp/angular.json
  DepartureBoardWeb/ClientApp/src/app/Pages/germany/germany-boards/germany-board-row/germany-board-row.component.html
  DepartureBoardWeb/ClientApp/src/app/Pages/germany/germany-boards/germany-boards.component.html
  DepartureBoardWeb/ClientApp/src/app/Pages/germany/germany-boards/germany-boards.component.ts
Labels: bug
