Repository benfl3713/DepartureBoard, pull requests merged in 2020-07, with the labels that each got.

#107 Update readme
  DepartureBoardWeb/wwwroot/preview.png
  README.md
Labels: documentation

#108 National Rail API as second optional data source
  .github/workflows/task-definition.json
  DepartureBoardWeb/ClientApp/src/app/Pages/boards/board/board.html
  DepartureBoardWeb/ClientApp/src/app/Pages/boards/board/board.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/boards/boards.component.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/home/home.component.html
  DepartureBoardWeb/ClientApp/src/app/Pages/singleboard/singleboard.ts
  DepartureBoardWeb/ClientApp/src/app/Services/departure.service.ts
  DepartureBoardWeb/ClientApp/src/app/settings/settings.component.html
  DepartureBoardWeb/ClientApp/src/app/settings/settings.component.ts
  DepartureBoardWeb/Controllers/LiveDeparturesController.cs
  DepartureBoardWeb/Startup.cs
  TrainDataAPI/ConfigService.cs
  TrainDataAPI/Connected Services/NationalRailService/ConnectedService.json
  TrainDataAPI/Connected Services/NationalRailService/Reference.cs
  TrainDataAPI/DataSource/ITrainDatasource.cs
  TrainDataAPI/DataSource/NationalRailAPI.cs
  TrainDataAPI/DataSource/RealTimeTrainsAPI.cs
  TrainDataAPI/DataSource/TransportAPI.cs
  TrainDataAPI/Departure.cs
  TrainDataAPI/TrainDataAPI.csproj
  TrainDataAPITests/DepartureTests.cs
Labels: enhancement

#116 Custom data date filter optional
  DepartureBoardWeb/ClientApp/src/app/Pages/boards/boards.component.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/custom-departure-board/add-custom-departure/add-custom-departure.component.html
  DepartureBoardWeb/ClientApp/src/app/Pages/custom-departure-board/add-custom-departure/add-custom-departure.component.ts
Labels: enhancement

#117 Added datasource analytics
  DepartureBoardWeb/ClientApp/src/app/settings/settings.component.ts
Labels: enhancement

#119 New Mobile Sidenav navigation
  DepartureBoardWeb/ClientApp/angular.json
  DepartureBoardWeb/ClientApp/package-lock.json
  DepartureBoardWeb/ClientApp/package.json
  DepartureBoardWeb/ClientApp/src/app/Pages/boards/boards.styling.css
  DepartureBoardWeb/ClientApp/src/app/app.component.html
  DepartureBoardWeb/ClientApp/src/app/nav-menu/nav-menu.component.css
  DepartureBoardWeb/ClientApp/src/app/nav-menu/nav-menu.component.html
  DepartureBoardWeb/ClientApp/src/app/nav-menu/nav-menu.component.ts
  DepartureBoardWeb/ClientApp/src/default.theme.scss
  DepartureBoardWeb/package-lock.json
Labels: enhancement

#130 Added robot.txt
  DepartureBoardWeb/wwwroot/robots.txt
  DepartureBoardWeb/wwwroot/sitemap.xml
Labels: technical

#132 Added coming soon widget
  DepartureBoardWeb/ClientApp/src/app/Pages/home/home.component.css
  DepartureBoardWeb/ClientApp/src/app/Pages/home/home.component.html
  DepartureBoardWeb/ClientApp/src/app/Services/Config.ts
  DepartureBoardWeb/ClientApp/src/app/app.module.ts
  DepartureBoardWeb/ClientApp/src/app/widgets/coming-soon/coming-soon.component.css
  DepartureBoardWeb/ClientApp/src/app/widgets/coming-soon/coming-soon.component.html
  DepartureBoardWeb/ClientApp/src/app/widgets/coming-soon/coming-soon.component.spec.ts
  DepartureBoardWeb/ClientApp/src/app/widgets/coming-soon/coming-soon.component.ts
Labels: enhancement

#133 Changed docker tags
  .github/workflows/pipeline.yml
Labels: technical

#134 Fixed docker tagging
  .github/workflows/pipeline.yml
Labels: technical
