Repository benfl3713/DepartureBoard, pull requests merged in 2021-03, with the labels that each got.

#188 Added Custom Departure UI
  DepartureBoardWeb/ClientApp/package-lock.json
  DepartureBoardWeb/ClientApp/package.json
  DepartureBoardWeb/ClientApp/src/app/Components/edit-custom-departure/edit-custom-departure.component.css
  DepartureBoardWeb/ClientApp/src/app/Components/edit-custom-departure/edit-custom-departure.component.html
  DepartureBoardWeb/ClientApp/src/app/Components/edit-custom-departure/edit-custom-departure.component.spec.ts
  DepartureBoardWeb/ClientApp/src/app/Components/edit-custom-departure/edit-custom-departure.component.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/boards/board/board.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/boards/boards.component.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/custom-departure-board/add-custom-departure/add-custom-departure.component.html
  DepartureBoardWeb/ClientApp/src/app/Pages/custom-departure-board/add-custom-departure/add-custom-departure.component.ts
  DepartureBoardWeb/ClientApp/src/app/app.module.ts
  DepartureBoardWeb/ClientApp/src/app/models/custom-departure.model.ts
  DepartureBoardWeb/ClientApp/src/app/widgets/coming-soon/coming-soon.component.html
  DepartureBoardWeb/ClientApp/src/app/widgets/coming-soon/coming-soon.items.ts
  DepartureBoardWeb/ClientApp/src/app/widgets/news/news.component.html
  DepartureBoardWeb/ClientApp/src/app/widgets/news/news.items.ts
  README.md
Labels: enhancement

#192 Fixed Loading Departures first time
  DepartureBoardWeb/ClientApp/src/app/Pages/boards/boards.component.ts
Labels: bug

#193 Added External API support
  DepartureBoardWeb/ClientApp/src/app/Components/departure-scroller/departure-scroller.component.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/boards/board/board.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/germany/germany-boards/germany-board-row/germany-board-row.component.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/germany/germany-singleboard/germany-singleboard.component.ts
  DepartureBoardWeb/ClientApp/src/app/Pages/singleboard/singleboard.ts
  DepartureBoardWeb/ClientApp/src/app/Services/bus-departure.service.ts
  DepartureBoardWeb/ClientApp/src/app/Services/departure.service.ts
  DepartureBoardWeb/ClientApp/src/app/Services/station-lookup.service.ts
  DepartureBoardWeb/ClientApp/src/app/search/search.component.ts
  DepartureBoardWeb/ClientApp/src/environments/environment.prod.ts
  DepartureBoardWeb/ClientApp/src/environments/environment.ts
  DepartureBoardWeb/Startup.cs
Labels: enhancement, technical
